# External plugins
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
---
gems:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - "/vendor/"

# Site settings
title: Developer Life
subtitle: ""
email: jsh28001@gmail.com
name: Suho Jang
description: 'The life of a developer who always needs to study'
baseurl: ""
url: "https://suhojang.github.io/"
plugins_dir:
  - jekyll-sitemap
cover: "/assets/main_cover.jpg"
logo: "/assets/logo.png"
markdown: kramdown
highlighter: rouge
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true
highlightjs_theme: "monokai-sublime"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  comments: true
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'
    
disqus_shortname: suhojang
ga_tracking_id: UA-83878761-1

descriptions:
  - cat: jekyll
    desc: "Developer Life"
social:
  - name: GitHub
    icon: github
    username: suhojang
    url: https://github.com/suhojang
    desc: Fork me on GitHub
    share: false

protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"
    twitter_image: "/assets/logo.png"
    os_repo: "https://github.com/bencentra/centrarium.com"
    os_rcs_type: "git"
    os_src: "git@github.com:bencentra/centrarium.com.git"
